apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-flask-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-flask
  template:
    metadata:
      labels:
        app: nginx-flask
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d
      - name: flask
        image: priyanshuprafful/devops-cloud-lab:latest
        ports:
        - containerPort: 5000
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
