name: Build, Push and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: priyanshuprafful/devops-cloud-lab:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Stop and remove existing container
            docker stop devops-flask || true
            docker rm devops-flask || true
            
            # Pull latest image
            docker pull priyanshuprafful/devops-cloud-lab:latest
            
            # Run new container
            docker run -d -p 5000:5000 --name devops-flask priyanshuprafful/devops-cloud-lab:latest
            
            # Clean up old images (optional)
            docker image prune -f
